# Generated by Django 4.1.7 on 2023-05-02 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_orderitem_rated'),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='order_item',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='oder_item_rating', to='item.orderitem'),
            preserve_default=False,
        ),
    ]
