# Generated by Django 4.1.3 on 2023-03-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=300.0),
            preserve_default=False,
        ),
    ]
