# Generated by Django 4.1.7 on 2023-04-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_discount_price_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
