# Generated by Django 4.1.7 on 2023-04-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(null=True),
        ),
    ]
