# Generated by Django 4.1.7 on 2023-05-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_item_average_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='rated',
            field=models.BooleanField(default=False),
        ),
    ]
