# Generated by Django 4.1.7 on 2023-05-10 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_orderitem_rated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
